title: "Rachid Abou Djamal Hamadou — Data Science & AI"
description: "Portfolio showcasing projects in data science, AI, cloud, and analytics."
baseurl: "/rachidaboudjamalhamadou"
url: "https://tole-corne.github.io"
markdown: kramdown
theme: null
plugins: []

defaults:
  - scope:
      path: ""
    values:
      layout: default

author: "Rachid Abou Djamal Hamadou"
github_username: "tole-corne"

exclude:
  - "README.md"
